# Generated by Django 4.2.4 on 2023-08-19 06:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mptt.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("files", "0002_alter_file_file"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="file",
            options={"verbose_name": "Файл", "verbose_name_plural": "Файлы"},
        ),
        migrations.RemoveField(
            model_name="file",
            name="title",
        ),
        migrations.AddField(
            model_name="file",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата создания"
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="filesize",
            field=models.PositiveIntegerField(default=1, verbose_name="Размер файла"),
        ),
        migrations.AddField(
            model_name="file",
            name="label",
            field=models.TextField(
                default="no title", max_length=255, verbose_name="Название"
            ),
        ),
        migrations.AddField(
            model_name="file",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Folder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.TextField(max_length=100, verbose_name="Название")),
                ("lft", models.PositiveIntegerField(editable=False)),
                ("rght", models.PositiveIntegerField(editable=False)),
                ("tree_id", models.PositiveIntegerField(db_index=True, editable=False)),
                ("level", models.PositiveIntegerField(editable=False)),
                (
                    "parent",
                    mptt.fields.TreeForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="files.folder",
                        verbose_name="Родительская папка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Папка",
                "verbose_name_plural": "Папки",
            },
        ),
        migrations.AddField(
            model_name="file",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="files.folder",
                verbose_name="Папка",
            ),
        ),
    ]
