# Generated by Django 4.2.4 on 2023-08-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0003_alter_file_options_remove_file_title_file_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="label",
            field=models.CharField(
                default="no title", max_length=255, verbose_name="Название"
            ),
        ),
        migrations.AlterField(
            model_name="folder",
            name="label",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
    ]
