# Generated by Django 4.2.4 on 2023-09-07 04:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0005_folder_date_alter_file_filesize"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(
                upload_to="files/storages/<property object at 0x000001765A3B9900>/"
            ),
        ),
    ]
