# Generated by Django 4.2.4 on 2023-09-08 12:18

from django.db import migrations, models
import files.models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0008_alter_file_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="comment",
            field=models.CharField(
                max_length=255, null=True, verbose_name="Комментарий к файлу"
            ),
        ),
        migrations.AlterField(
            model_name="file",
            name="file",
            field=models.FileField(upload_to=files.models.file_path),
        ),
    ]
