# Generated by Django 4.2.4 on 2023-11-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0009_file_comment_alter_file_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="share",
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
