# Generated by Django 4.2.4 on 2023-11-03 08:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0011_alter_file_share"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="share",
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
