# Generated by Django 4.2.4 on 2023-11-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("files", "0012_alter_file_share"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="url",
            field=models.URLField(
                max_length=1024, null=True, verbose_name="Ссылка на файл"
            ),
        ),
    ]
